AWSTemplateFormatVersion: 2010-09-09
Description: Create the Cross-Account IAM Prowler Role
Parameters:
  ProwlerCrossAccountRole:
    Type: String
    Description: >-
      Enter Name for CrossAccount Role to be created for Prowler to assess all
      Accounts in the AWS Organization.
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: >-
      Max 64 alphanumeric characters. Also special characters supported [+, =,
      ., @, -]
    Default: ProwlerXA-Role
Resources:
  ProwlerRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: >-
        Provides Prowler EC2 instance permissions to assess security of Accounts in AWS Organization
      RoleName: !Ref ProwlerCrossAccountRole
      Tags:
        - Key: App
          Value: Prowler
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringLike:
                "aws:PrincipalArn": !Sub >-
                  arn:${AWS::Partition}:iam::${AWS::AccountId}:user/Abayomi
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/SecurityAudit"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess"
      Policies:
        - PolicyName: Prowler-Additions-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowMoreReadForProwler
                Effect: Allow
                Resource: "*"
                Action:
                  - "access-analyzer:List*"
                  - "apigateway:Get*"
                  - "apigatewayv2:Get*"
                  - "aws-marketplace:ViewSubscriptions"
                  - "dax:ListTables"
                  - "ds:ListAuthorizedApplications"
                  - "ds:DescribeRoles"
                  - "ec2:GetEbsEncryptionByDefault"
                  - "ecr:Describe*"
                  - "lambda:GetAccountSettings"
                  - "lambda:GetFunctionConfiguration"
                  - "lambda:GetLayerVersionPolicy"
                  - "lambda:GetPolicy"
                  - "opsworks-cm:Describe*"
                  - "opsworks:Describe*"
                  - "secretsmanager:ListSecretVersionIds"
                  - "sns:List*"
                  - "sqs:ListQueueTags"
                  - "states:ListActivities"
                  - "support:Describe*"
                  - "tag:GetTagKeys"
