name: "Terraform"

on: [push]

jobs:
  deploy:
    name: Prowler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Requirements
        run: |
          pip install detect-secrets
          sudo apt install jq

      - name: Terraform initialize
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan & Apply
        id: plan
        run: |
          terraform plan
          terraform apply --auto-approve
      - name: Clone Prowler Repo
        run: |
          git clone https://github.com/toniblyx/prowler
          cd prowler
          ls -al
      - name: Sleep
        run: |
          sleep 7m
      - name: Destroy Resource
        run: |
          terraform destroy --auto-approve
