name: "Terraform"

on: [push]

jobs:
  deploy:
    name: Prowler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get AWS Version
        run: |
          aws --version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform initialize
        run: terraform init

      - id: plan
        run: |
          terraform plan -no-color
          terraform plan
